language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "8"
script:
  - npm run lint:test
  - npm run benchmark:console
cache:
  yarn: true
  directories:
    - node_modules
after_success: 'npm run coveralls'
