language: node_js
node_js:
  - "6"
  - "8"
  - "9"
  - "10"
script:
  - npm run lint:test
  - 'bash bin/run_report.sh'
cache:
  yarn: true
  directories:
    - node_modules
after_success: 
  - 'npm run coveralls'
  - 'bash bin/commit.sh'
